[package]
name = "cyfile"
version = "0.5.2"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["lib"]

[dependencies]
chrono = "0.4.42"
image = "0.25.9"
scraper = "0.24.0"
thiserror = "2.0.17"

[dev-dependencies]
anyhow = "1.0.100"
tempfile = "3.23.0"
