[package]
name = "cyfile"
version = "0.5.1"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["lib"]

[dependencies]
chrono = "0.4.41"
image = "0.25.8"
scraper = "0.24.0"
thiserror = "2.0.16"

[dev-dependencies]
anyhow = "1.0.99"
tempfile = "3.21.0"
